import Head from "next/head";
import styles from '../styles/Home.module.css'

export default function Blog() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Blog Next App</title>
        <meta name="description" content="Generated by create next app blog" />
        <link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Blog Page</h1>
			<a href="http://localhost:3000/">Back to home</a>
		</div>
	)
}